# Data Analysis 2 Hw2

In [2]:
import warnings

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from plotnine import *
from skimpy import skim
from stargazer.stargazer import Stargazer

%matplotlib inline
warnings.filterwarnings("ignore")

In [11]:
#hotels_europe_price = pd.read_csv("https://osf.io/p6tyr/download")
#hotels_europe_features = pd.read_csv("https://osf.io/utwjs/download")

hotels_europe_price = pd.read_csv("hotels-europe_price (1).csv")
hotels_europe_features = pd.read_csv("hotels-europe_features (1).csv")

#join
europe = hotels_europe_price.merge(hotels_europe_features, on = "hotel_id")
europe.head()

#create a new variable
europe["highly_rated"] = np.where(europe["rating"] >= 4, 1, 0)
europe.head(10)

#filter the city: Salzburg
salzburg = (
    europe.loc[lambda x: x["accommodation_type"] == "Hotel"]
    .loc[lambda x: x["city_actual"] == "Salzburg"]
    .loc[lambda x: x["stars"].notnull()]
)

salzburg

,hotel_id,price,offer,offer_cat,year,month,weekend,holiday,nnights,scarce_room,...,city_actual,rating_reviewcount,center1label,center2label,neighbourhood,ratingta,ratingta_count,distance_alter,accommodation_type,highly_rated
127748,20151,164,1,1-15% offer,2018,2,1,0,1,1,...,Salzburg,61.0,City centre,Smaragd II Ski Lift,Altstadt,4.5,140.0,51.0,Hotel,1
127749,20151,173,0,0% no offer,2017,11,0,0,1,1,...,Salzburg,61.0,City centre,Smaragd II Ski Lift,Altstadt,4.5,140.0,51.0,Hotel,1
127750,20151,733,0,0% no offer,2017,12,0,1,4,1,...,Salzburg,61.0,City centre,Smaragd II Ski Lift,Altstadt,4.5,140.0,51.0,Hotel,1
127751,20152,2047,0,0% no offer,2017,12,0,1,4,0,...,Salzburg,107.0,City centre,Smaragd II Ski Lift,Altstadt,4.5,1018.0,50.0,Hotel,1
127752,20152,319,1,15-50% offer,2017,11,0,0,1,1,...,Salzburg,107.0,City centre,Smaragd II Ski Lift,Altstadt,4.5,1018.0,50.0,Hotel,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129150,20427,61,1,50%-75% offer,2017,11,0,0,1,1,...,Salzburg,36.0,City centre,Smaragd II Ski Lift,Schallmoos,2.0,71.0,51.0,Hotel,0
129151,20427,489,1,1-15% offer,2017,12,0,1,4,1,...,Salzburg,36.0,City centre,Smaragd II Ski Lift,Schallmoos,2.0,71.0,51.0,Hotel,0
129152,20427,88,1,15-50% offer,2018,6,1,0,1,0,...,Salzburg,36.0,City centre,Smaragd II Ski Lift,Schallmoos,2.0,71.0,51.0,Hotel,0
129153,20427,91,1,15-50% offer,2018,5,1,0,1,0,...,Salzburg,36.0,City centre,Smaragd II Ski Lift,Schallmoos,2.0,71.0,51.0,Hotel,0
129154,20427,72,1,15-50% offer,2018,4,1,0,1,0,...,Salzburg,36.0,City centre,Smaragd II Ski Lift,Schallmoos,2.0,71.0,51.0,Hotel,0

In [ ]:
# Check for missing values
salzburg.isna().sum()

hotel_id              0
price                 0
offer                 0
offer_cat             0
year                  0
month                 0
weekend               0
holiday               0
nnights               0
scarce_room           0
city                  0
distance              0
stars                 0
rating                0
country               0
city_actual           0
rating_reviewcount    0
center1label          0
center2label          0
neighbourhood         0
ratingta              0
ratingta_count        0
distance_alter        0
accommodation_type    0
highly_rated          0
dtype: int64

In [17]:
salzburg = salzburg[["highly_rated", "distance","neighbourhood","accommodation_type"]]
salzburg.head(5)

        highly_rated  distance neighbourhood accommodation_type
127748             1       0.6      Altstadt              Hotel
127749             1       0.6      Altstadt              Hotel
127750             1       0.6      Altstadt              Hotel
127751             1       0.3      Altstadt              Hotel
127752             1       0.3      Altstadt              Hotel

In [ ]:
salzburg_clean = salzburg.drop_duplicates()
salzburg_clean